[target.aarch64-unknown-linux-gnu]
pre-build = [
    "apt-get update && apt-get install --assume-yes --no-install-recommends build-essential perl wget",
    "mkdir -p /usr/local/src && cd /usr/local/src && wget -q https://github.com/openssl/openssl/releases/download/openssl-3.0.13/openssl-3.0.13.tar.gz && tar xzf openssl-3.0.13.tar.gz && cd openssl-3.0.13 && ./Configure linux-aarch64 --cross-compile-prefix=aarch64-linux-gnu- --prefix=/usr --libdir=lib/aarch64-linux-gnu --openssldir=/usr/local/ssl shared && make -s -j$(nproc) && make install_sw",
]
